baseURL= "https://shrey.github.io/"
title = "Shrey Gupta"
theme = "PaperMod"

[params]
  env = "production"
  title = "Shrey Gupta"
  description = "Personal website and blog"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "Shrey Gupta"
  images = ["/img/icon.jpg"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  enableLatex = true

  [params.assets]
    favicon = "/img/icon.jpg"
    favicon16x16 = "/img/icon.jpg"
    favicon32x32 = "/img/icon.jpg"
    apple_touch_icon = "/img/icon.jpg"
    safari_pinned_tab = "/img/icon.jpg"
    customCSS = ["css/extended/fontsize.css"]

  [params.label]
    text = "Shrey Gupta"

  [params.profileMode]
    enabled = true
    title = "Shrey Gupta"
    imageUrl = "/img/icon.jpg"
    imageWidth = 180
    imageHeight = 180
    imageTitle = "Profile Picture"
    subtitle = "Welcome to my personal website"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:your.email@example.com"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/shreygupta"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/posts/"
    weight = 30
  [[menu.main]]
    identifier = "5-9"
    name = "5-9"
    url = "/5-9/"
    weight = 40
  [[menu.main]]
    identifier = "reading"
    name = "reading"
    url = "/reading/"
    weight = 50

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
